/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Nana
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edLista = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        btOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("SISTEMA GERENCIADOR DE COMPRAS ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setText("NOME DA MERCADORIA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel3.setText("LISTAGEM DE MERCADORIAS CADASTRADAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        edNome.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jPanel1.add(edNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 220, 30));

        edLista.setColumns(20);
        edLista.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        edLista.setRows(5);
        jScrollPane1.setViewportView(edLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 610, -1));

        btSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btSalvar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        btEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btEliminar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        btEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btEliminar.setText("ELIMINAR LISTA");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        btExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btExcluir.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        btEditar.setBackground(new java.awt.Color(255, 255, 255));
        btEditar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        btEditar.setText("EDITAR");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        btListar.setBackground(new java.awt.Color(255, 255, 255));
        btListar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        btListar.setText("LISTAR");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });
        jPanel1.add(btListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, -1));

        btOrdenar.setBackground(new java.awt.Color(255, 255, 255));
        btOrdenar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        btOrdenar.setText("ORDENAR");
        btOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<String> listaMercadoria = new ArrayList<String>();
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (!(edNome.getText().equals(""))){
        listaMercadoria.add(edNome.getText());
        JOptionPane.showMessageDialog(null, "A mercadoria " + edNome.getText()
            + " foi salva!");
        edNome.setText(null);
        edNome.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "Insira a mercadoria!");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        String merc = "";
        if (!listaMercadoria.isEmpty()){
            for (int i = 0; i<listaMercadoria.size(); i++){
                merc = merc +(i+1)+"º:"+listaMercadoria.get(i) + "\n";
            }
        }else{
            JOptionPane.showMessageDialog(null, "Não existe mercadoria cadastrada!");
        }
        edLista.setText(merc);
    }//GEN-LAST:event_btListarActionPerformed

    private void btOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarActionPerformed
    if (!listaMercadoria.isEmpty()){
        Collections.sort(listaMercadoria);
        JOptionPane.showMessageDialog(null, "Lista organizada!");
    }else{
        JOptionPane.showMessageDialog(null,"Impossível organizar - Lista vazia!");
    }
    }//GEN-LAST:event_btOrdenarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
    if(listaMercadoria.isEmpty()){
        JOptionPane.showMessageDialog(null, "Impossível deletar. Não há itens.");
    }else{
        int i = Integer.parseInt(JOptionPane.showInputDialog(null,"Qual item deseja excluir?"));
        if(i>0 && i<=listaMercadoria.size()){
            JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
        }else{
            JOptionPane.showMessageDialog(null, "Produto não cadastrado!");
        }
    }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
    if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir sua lista?"+
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        listaMercadoria.clear();
        JOptionPane.showMessageDialog(null, "Ação concluída!");
    }else{
        JOptionPane.showMessageDialog(null, "Ação cancelada!");
    }
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
    int i = Integer.parseInt(JOptionPane.showInputDialog("Qual item deseja editar?"));
    if(i>0 && i<=listaMercadoria.size()){
        if(JOptionPane.showConfirmDialog(null,
                "Tem certeza que deseja editar?"+listaMercadoria.get(i-1),"Confirme",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            String novoNome = JOptionPane.showInputDialog("Informar novo nome: ");
            listaMercadoria.set(i-1, novoNome);
        }else{
            JOptionPane.showMessageDialog(null, "Ação cancelada!");
        }
    }else{
       JOptionPane.showMessageDialog(null, "Mercadoria não existente!"); 
    }
    }//GEN-LAST:event_btEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btOrdenar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextArea edLista;
    private javax.swing.JTextField edNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
